# Lazygit Configuration - Kanagawa Theme
gui:
  theme:
    activeBorderColor:
      - '#7E9CD8'
      - bold
    inactiveBorderColor:
      - '#54546D'
    searchingActiveBorderColor:
      - '#E6C384'
      - bold
    optionsTextColor:
      - '#DCD7BA'
    selectedLineBgColor:
      - '#2D4F67'
    cherryPickedCommitBgColor:
      - '#957FB8'
    cherryPickedCommitFgColor:
      - '#DCD7BA'
    unstagedChangesColor:
      - '#E82424'
    defaultFgColor:
      - '#DCD7BA'
    selectedRangeBgColor:
      - '#2D4F67'
  showFileTree: true
  showRandomTip: false
  showCommandLog: false

git:
  paging:
    colorArg: always
  commit:
    signOff: false
  merging:
    manualCommit: false
    args: ""

keybinding:
  universal:
    quit: q
    quit-alt1: <c-c>
    return: <esc>
    prevItem: <up>
    nextItem: <down>
    prevItem-alt: k
    nextItem-alt: j
    prevPage: ','
    nextPage: '.'
    scrollLeft: H
    scrollRight: L
    gotoTop: <
    gotoBottom: '>'
    togglePanel: <tab>
    prevBlock: <left>
    nextBlock: <right>
    prevBlock-alt: h
    nextBlock-alt: l
